ALTER TABLE "competitions" ADD COLUMN "minimum_participant_entries" integer;--> statement-breakpoint
ALTER TABLE "competitions" ADD COLUMN "participant_confirmation_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "competitions" ADD COLUMN "participation_confirmed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "competitions" ADD COLUMN "cancelled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "competitions" ADD COLUMN "cancellation_reason" text;--> statement-breakpoint
ALTER TABLE "competitions" ADD CONSTRAINT "competitions_minimum_participation_non_negative_chk" CHECK ("competitions"."minimum_participant_entries" IS NULL OR "competitions"."minimum_participant_entries" >= 0);--> statement-breakpoint
ALTER TABLE "competitions" ADD CONSTRAINT "competitions_participant_confirmation_order_chk" CHECK ("competitions"."participant_confirmation_at" IS NULL OR (("competitions"."registration_end_at" IS NULL OR "competitions"."registration_end_at" <= "competitions"."participant_confirmation_at") AND ("competitions"."event_start_at" IS NULL OR "competitions"."participant_confirmation_at" < "competitions"."event_start_at")));--> statement-breakpoint
ALTER TABLE "competitions" ADD CONSTRAINT "competitions_cancellation_state_chk" CHECK (("competitions"."cancelled_at" IS NULL AND "competitions"."cancellation_reason" IS NULL) OR ("competitions"."cancelled_at" IS NOT NULL AND "competitions"."cancellation_reason" = 'insufficient_participants' AND "competitions"."status" = 'published' AND "competitions"."minimum_participant_entries" >= 1 AND "competitions"."participant_confirmation_at" IS NOT NULL AND "competitions"."event_start_at" IS NOT NULL AND "competitions"."cancelled_at" >= "competitions"."participant_confirmation_at" AND "competitions"."cancelled_at" < "competitions"."event_start_at"));--> statement-breakpoint
ALTER TABLE "competitions" ADD CONSTRAINT "competitions_participation_confirmation_state_chk" CHECK ("competitions"."participation_confirmed_at" IS NULL OR ("competitions"."status" = 'published' AND "competitions"."minimum_participant_entries" >= 1 AND "competitions"."participant_confirmation_at" IS NOT NULL AND "competitions"."event_start_at" IS NOT NULL AND "competitions"."participation_confirmed_at" >= "competitions"."participant_confirmation_at" AND "competitions"."participation_confirmed_at" < "competitions"."event_start_at" AND "competitions"."cancelled_at" IS NULL));--> statement-breakpoint
ALTER TABLE "competitions" ADD CONSTRAINT "competitions_participation_terminal_state_chk" CHECK ("competitions"."cancelled_at" IS NULL OR "competitions"."participation_confirmed_at" IS NULL);
