import { assertServerOnly } from "@/server/runtime/assert-server-only";

assertServerOnly("server/auth/mfa/mfa-core");

// Shared constants and the error type for the MFA lifecycle. Thresholds live here — never inlined
// at a call site — mirroring rate-limit-constants.ts's convention for the auth rate limiters.

// Consecutive failures (TOTP challenge OR recovery-code attempts share this ONE counter, since
// both are "prove you are the operator" attempts against the same factor) before the factor locks.
export const MFA_LOCKOUT_THRESHOLD = 5;

// How long a lockout holds once engaged.
export const MFA_LOCKOUT_SECONDS = 15 * 60;

// Acceptance window either side of the current 30s step (±1 step = 90s total tolerance), covering
// ordinary clock drift between the operator's device and the server without materially widening
// the guessable window.
export const TOTP_WINDOW_STEPS = 1;

export const RECOVERY_CODE_COUNT = 10;

// 128 bits of entropy per code — generated by us, never chosen by a human, so a fast SHA-256 lookup
// hash is the correct mechanism (see mfa_recovery_codes' schema comment); there is no low-entropy
// guessing surface a slow KDF would be defending against.
export const RECOVERY_CODE_BYTE_LENGTH = 16;

export const MFA_EVENT = {
  enrolled: "mfa.enrolled",
  reset: "mfa.reset",
  recoveryCodeUsed: "mfa.recovery_code_used",
  lockedOut: "mfa.locked_out",
} as const;

export type MfaErrorCode =
  | "mfa_already_enrolled"
  | "mfa_enrolment_not_found"
  | "mfa_not_enrolled"
  | "mfa_invalid_code"
  | "mfa_invalid_recovery_code"
  | "mfa_locked_out"
  | "mfa_elevation_unavailable";

export class MfaError extends Error {
  /**
   * `retryAfterSeconds` is set whenever the account is under a timed lock AFTER this error — which
   * includes the invalid-code attempt that engaged the lock, not only the refusals that follow it.
   * Without it the operator whose fifth wrong code locks the account is told only "invalid code" and
   * is left guessing why the sixth attempt behaves differently; the lock is a consequence of their
   * action and they have to be able to read it. It rides alongside the code rather than replacing it
   * because that attempt genuinely WAS an invalid code — the lock is its side effect.
   */
  constructor(
    public readonly code: MfaErrorCode,
    public readonly status: 401 | 403 | 404 | 409 | 423 | 503,
    message: string,
    public readonly retryAfterSeconds: number | null = null,
  ) {
    super(message);
    this.name = "MfaError";
  }
}
