import { createHash, randomBytes } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import type { Database } from "@/server/db/client";
import { mfaRecoveryCodes } from "@/server/db/schema";
import { assertServerOnly } from "@/server/runtime/assert-server-only";
import { base32Encode } from "./base32";
import { RECOVERY_CODE_BYTE_LENGTH, RECOVERY_CODE_COUNT } from "./mfa-core";

assertServerOnly("server/auth/mfa/recovery-service");

// Ten single-use recovery codes, generated once at enrolment confirmation and shown exactly once —
// callers must capture the return value there, because nothing re-displays them afterward.
//
// A code is generated by us from a CSPRNG (128 bits), never chosen by a human, so there is no
// low-entropy guessing surface a slow KDF (bcrypt-class) would be defending against; a plain
// SHA-256 lookup by hash is both correct and O(1) via the unique index on mfa_recovery_codes.

// Codes are displayed as five dash-grouped blocks for readability but STORED and COMPARED in their
// canonical undashed uppercase form, so redemption input in either shape hashes identically.
const normalizeRecoveryCode = (input: string): string => {
  return input
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, "");
};

const hashRecoveryCode = (canonical: string): string => {
  return createHash("sha256").update(canonical).digest("hex");
};

const formatRecoveryCodeForDisplay = (canonical: string): string => {
  return canonical.match(/.{1,4}/g)?.join("-") ?? canonical;
};

/**
 * Replaces every recovery code for `userId` with a fresh set of ten, inside the caller's
 * transaction. Returns the PLAINTEXT display-formatted codes — the only moment they exist outside
 * a hash. Deleting any previous codes first means a re-enrolment (recovery-code redemption forces
 * one) can never leave a stale code from an earlier factor still redeemable.
 */
export const issueRecoveryCodesInTransaction = async (
  tx: Database,
  userId: string,
  now: Date,
): Promise<string[]> => {
  await tx.delete(mfaRecoveryCodes).where(eq(mfaRecoveryCodes.userId, userId));

  const displayCodes: string[] = [];
  const rows: (typeof mfaRecoveryCodes.$inferInsert)[] = [];

  for (let i = 0; i < RECOVERY_CODE_COUNT; i += 1) {
    const canonical = base32Encode(randomBytes(RECOVERY_CODE_BYTE_LENGTH));
    displayCodes.push(formatRecoveryCodeForDisplay(canonical));
    rows.push({ userId, codeHash: hashRecoveryCode(canonical), createdAt: now });
  }

  await tx.insert(mfaRecoveryCodes).values(rows);

  return displayCodes;
};

/**
 * Atomically finds-and-consumes an unused recovery code for `userId` in ONE conditional UPDATE — a
 * SELECT-then-UPDATE pair would let two concurrent redemptions of the SAME leaked code both read
 * "unused" before either commits (READ COMMITTED does not lock a plain SELECT), so the second caller
 * would re-delete an already-deleted factor as a no-op and re-stamp `users.mfa_invalidated_at` with
 * its own request-captured `now` — which could regress that timestamp BACKWARD relative to the first
 * caller's, letting a JWT whose cached claim falls in between incorrectly read as `satisfied` again.
 * The `usedAt IS NULL` predicate inside the UPDATE's WHERE clause is what closes this: Postgres
 * re-evaluates the WHERE clause against the freshly-committed row before a blocked UPDATE proceeds,
 * so the second caller's own UPDATE matches zero rows once the first has committed, and this
 * correctly reports "already used" rather than accepting a stale read. This is Rule 25's
 * single-row case: a state transition on one existing row belongs in a compare-and-set WHERE
 * clause, not in an application-computed read-modify-write.
 */
export const consumeRecoveryCode = async (
  tx: Database,
  userId: string,
  rawCode: string,
  now: Date,
): Promise<{ id: string } | null> => {
  const codeHash = hashRecoveryCode(normalizeRecoveryCode(rawCode));

  const [consumed] = await tx
    .update(mfaRecoveryCodes)
    .set({ usedAt: now })
    .where(
      and(
        eq(mfaRecoveryCodes.userId, userId),
        eq(mfaRecoveryCodes.codeHash, codeHash),
        isNull(mfaRecoveryCodes.usedAt),
      ),
    )
    .returning({ id: mfaRecoveryCodes.id });

  return consumed ?? null;
};
